Repository DecipherNow/gm-fabric-dashboard, pull requests merged in 2018-02, with the labels that each got.

#1561 fix: resolve issues with safari/edge/ie
  .circleci/config.yml
  e2e-tests/tests/base-instance-view.js
  e2e-tests/tests/fabric-view.js
  e2e-tests/tests/instance-view-go.js
  e2e-tests/tests/instance-view-jvm.js
  e2e-tests/tests/service-view.js
  e2e-tests/view-models/instance-go-view-model.js
  scripts/testcafe.js
Labels: priority-1

#1567 feat: update base colors
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Button/__snapshots__/Button.test.js.snap
  src/components/ConfirmationModal/__snapshots__/ConfirmationModal.test.js.snap
  src/components/Main/components/NotFoundError/components/__snapshots__/ErrorContent.test.js.snap
  src/components/Main/components/Table/components/__snapshots__/TableLineItem.test.js.snap
  src/style/styleVariables.js
Labels: priority-2

#1568 feat: improved badge style
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Main/components/SparklineCol.js
  src/components/Main/components/Table/__snapshots__/Table.test.js.snap
  src/components/Main/components/Table/components/__snapshots__/TableLineItem.test.js.snap
  src/components/Main/components/VizBar.js
  src/components/Main/components/VizFill.js
  src/components/Main/components/__snapshots__/SparklineCol.test.js.snap
  src/components/Main/components/__snapshots__/VizBar.test.js.snap
  src/components/Main/components/__snapshots__/VizFill.test.js.snap
  src/components/Main/scenes/InstanceView/components/Badge.js
  src/components/Main/scenes/InstanceView/components/Routes/__snapshots__/RoutesGrid.test.js.snap
  src/components/Main/scenes/InstanceView/components/__snapshots__/Badge.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/__snapshots__/FunctionsGrid.test.js.snap
Labels: priority-3

#1574 feat: improved footer readability
  src/components/Footer/components/Copyright.js
  src/components/Footer/components/__snapshots__/Copyright.test.js.snap
Labels: priority-3

#1578 feat: remove transition on react-grid load
  src/components/Main/components/GMGrid/style/ReactGridLayout.js
Labels: priority-3

#1579 feat: improved line chart style
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Main/components/GMLineChart/GMLineChart.js
  src/components/Main/components/GMLineChart/__snapshots__/GMLineChart.test.js.snap
  src/components/Main/components/GMLineChart/components/LineChartContent.js
  src/components/Main/components/GMLineChart/components/LineChartDisplay.js
  src/components/Main/components/GMLineChart/components/LineChartEmpty.js
  src/components/Main/components/GMLineChart/components/LineChartTitle.js
  src/components/Main/components/GMLineChart/components/__snapshots__/LineChartContent.test.js.snap
  src/components/Main/components/GMLineChart/components/__snapshots__/LineChartDisplay.test.js.snap
  src/components/Main/components/GMLineChart/components/__snapshots__/LineChartEmpty.test.js.snap
  src/components/Main/components/GMLineChart/components/__snapshots__/LineChartTitle.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/__snapshots__/Summary.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/__snapshots__/Summary.test.js.snap
Labels: priority-3

#1576 feat: improved explorer page
  src/components/Main/components/Explorer/__snapshots__/explorer.test.js.snap
  src/components/Main/components/Explorer/components/Inspector/Inspector.js
  src/components/Main/components/Explorer/components/Inspector/__snapshots__/Inspector.test.js.snap
  src/components/Main/components/Explorer/components/Inspector/components/InspectorLabel.js
  src/components/Main/components/Explorer/components/Inspector/components/InspectorSearch.js
  src/components/Main/components/Explorer/components/Inspector/components/__snapshots__/InspectorSearch.test.js.snap
Labels: priority-3

#1570 feat: improved app header style
  src/__snapshots__/Storyshots.test.js.snap
  src/components/AppHeader/__snapshots__/AppHeader.test.js.snap
  src/components/AppHeader/components/AppHeaderContainer.js
  src/components/AppHeader/components/AppToolBar/components/AppToolBarHeader.js
  src/components/AppHeader/components/AppToolBar/components/BrandText.js
  src/components/AppHeader/components/AppToolBar/components/Breadcrumb.js
  src/components/AppHeader/components/AppToolBar/components/__snapshots__/AppToolBarHeader.test.js.snap
  src/components/AppHeader/components/AppToolBar/components/__snapshots__/BrandText.test.js.snap
  src/components/AppHeader/components/AppToolBar/components/__snapshots__/Breadcrumb.test.js.snap
  src/components/AppHeader/components/Banner/components/HeaderContainer.js
  src/components/AppHeader/components/Banner/components/__snapshots__/HeaderContainer.test.js.snap
  src/components/AppHeader/components/__snapshots__/AppHeaderContainer.test.js.snap
  src/images/app-banner.png
  src/images/gmFabricLogoFake.svg
  src/images/mesh-long.png
  src/images/mesh-web.jpg
Labels: priority-3

#1575 feat: Improved layout sections
  src/__snapshots__/Storyshots.test.js.snap
  src/components/AppHeader/__snapshots__/AppHeader.test.js.snap
  src/components/AppHeader/components/AppToolBar/components/LanguageSelector/__snapshots__/LanguageSelector.test.js.snap
  src/components/AppHeader/components/AppToolBar/components/LanguageSelector/components/LanguageSelectorContent.js
  src/components/AppHeader/components/AppToolBar/components/LanguageSelector/components/LanguageSelectorWrap.js
  src/components/LayoutSection/LayoutSection.js
  src/components/LayoutSection/components/Header.js
  src/components/LayoutSection/components/LayoutSectionWrap.js
  src/components/LayoutSection/components/SectionContent.js
  src/components/LayoutSection/components/SectionIcon.js
  src/components/LayoutSection/components/__snapshots__/Header.test.js.snap
  src/components/LayoutSection/components/__snapshots__/LayoutSectionWrap.test.js.snap
  src/components/LayoutSection/components/__snapshots__/SectionContent.test.js.snap
  src/components/LayoutSection/components/__snapshots__/SectionIcon.test.js.snap
  src/components/Main/components/Settings/__snapshots__/SettingsGrid.test.js.snap
  src/components/Main/components/Settings/components/__snapshots__/PollingSettings.test.js.snap
  src/components/Main/scenes/FabricView/components/FabricGrid/components/FabricMainView/scene/ServicesCardsView/components/SectionContent.js
  src/components/Main/scenes/FabricView/components/FabricGrid/components/FabricMainView/scene/ServicesCardsView/components/SectionHeader.js
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Summary.js
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/__snapshots__/Summary.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/Summary.js
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/__snapshots__/Summary.test.js.snap
Labels: priority-3

#1577 feat: cleaner data display styles
  src/components/Main/components/GMGrid/components/DataDisplay.js
  src/components/Main/components/GMGrid/components/DataKey.js
  src/components/Main/components/GMGrid/components/DataPair.js
  src/components/Main/components/GMGrid/components/DataSparkline.js
  src/components/Main/components/GMGrid/components/DataValue.js
  src/components/Main/components/GMGrid/components/__snapshots__/DataDisplay.test.js.snap
  src/components/Main/components/GMGrid/components/__snapshots__/DataKey.test.js.snap
  src/components/Main/components/GMGrid/components/__snapshots__/DataKeyHeader.test.js.snap
  src/components/Main/components/GMGrid/components/__snapshots__/DataPair.test.js.snap
  src/components/Main/components/GMGrid/components/__snapshots__/DataSparkline.test.js.snap
  src/components/Main/components/GMGrid/components/__snapshots__/DataValue.test.js.snap
Labels: priority-3

#1580 feat: improve table styles
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Main/components/Table/__snapshots__/Table.test.js.snap
  src/components/Main/components/Table/components/TableLineItem.js
  src/components/Main/components/Table/components/__snapshots__/TableLineItem.test.js.snap
  src/components/Main/components/TableBody.js
  src/components/Main/components/TableDisplay.js
  src/components/Main/components/TableDrawerCollapse.js
  src/components/Main/components/TableHeader.js
  src/components/Main/components/TableRow.js
  src/components/Main/components/__snapshots__/TableBody.test.js.snap
  src/components/Main/components/__snapshots__/TableDisplay.test.js.snap
  src/components/Main/components/__snapshots__/TableHeader.test.js.snap
  src/components/Main/components/__snapshots__/TableRow.test.js.snap
  src/components/Main/scenes/InstanceView/components/Routes/__snapshots__/RoutesGrid.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/__snapshots__/FunctionsGrid.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/Threads/__snapshots__/threadsgrid.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/Threads/components/ThreadsTable/__snapshots__/ThreadsTable.test.js.snap
  src/components/Main/scenes/ServiceView/__snapshots__/ServiceView.test.js.snap
Labels: priority-3

#1560 test: add Spanish internationalization tests
  e2e-tests/tests/base-instance-view.js
  e2e-tests/tests/internationalization-spanish.js
  e2e-tests/view-models/base-instance-view-model.js
  e2e-tests/view-models/fabric-view-model.js
  e2e-tests/view-models/instance-go-view-model.js
  e2e-tests/view-models/instance-jvm-view-model.js
  e2e-tests/view-models/service-view-model.js
  e2e-tests/view-models/settings-view-model.js
Labels: priority-1

#1582 feat: restyled inputs
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Main/components/GMSearchInput.js
  src/components/Main/components/GMSelect/GMSelect.js
  src/components/Main/components/TableToolbar/__snapshots__/TableToolbar.test.js.snap
  src/components/Main/components/__snapshots__/GMSearchInput.test.js.snap
  src/components/Main/scenes/InstanceView/components/Routes/__snapshots__/RoutesGrid.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/GoInstanceView/scenes/Functions/__snapshots__/FunctionsGrid.test.js.snap
  src/components/Main/scenes/InstanceView/scenes/JVMInstanceView/scenes/Threads/__snapshots__/threadsgrid.test.js.snap
  src/components/Main/scenes/ServiceView/__snapshots__/ServiceView.test.js.snap
Labels: priority-3
